# Generated by Django 5.0.2 on 2025-04-08 21:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TripartiteInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "company_location",
                    models.CharField(max_length=64, verbose_name="公司所在地"),
                ),
                ("company_scale", models.CharField(max_length=32, verbose_name="公司规模")),
                ("salary", models.CharField(max_length=32, verbose_name="薪资")),
                ("job_name", models.CharField(max_length=30, verbose_name="岗位名称")),
                ("job_category", models.CharField(max_length=32, verbose_name="岗位类别")),
                (
                    "company_category",
                    models.CharField(max_length=32, verbose_name="公司类别"),
                ),
                ("school_name", models.CharField(max_length=64, verbose_name="学生所在学校")),
                ("college_name", models.CharField(max_length=32, verbose_name="学院")),
                ("major_name", models.CharField(max_length=32, verbose_name="专业名称")),
                ("student_name", models.CharField(max_length=20, verbose_name="学生姓名")),
                (
                    "student_id_card",
                    models.CharField(max_length=18, verbose_name="学生身份证号"),
                ),
                ("upload_time", models.DateTimeField(auto_now_add=True)),
                (
                    "student",
                    models.ForeignKey(
                        db_column="student_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app.students",
                    ),
                ),
            ],
        ),
    ]
