# Generated by Django 5.0.2 on 2025-04-09 16:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0002_tripartiteinfo"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="tripartiteinfo",
            table="tripartite_info",
        ),
    ]
