# Generated by Django 5.0.2 on 2025-04-09 17:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0003_alter_tripartiteinfo_table"),
    ]

    operations = [
        migrations.RenameField(
            model_name="tripartiteinfo",
            old_name="company_location",
            new_name="companyLocation",
        ),
        migrations.RenameField(
            model_name="tripartiteinfo",
            old_name="job_name",
            new_name="positionName",
        ),
        migrations.RenameField(
            model_name="tripartiteinfo",
            old_name="school_name",
            new_name="school",
        ),
        migrations.RenameField(
            model_name="tripartiteinfo",
            old_name="student_id_card",
            new_name="studentIdCard",
        ),
        migrations.RenameField(
            model_name="tripartiteinfo",
            old_name="student_name",
            new_name="studentName",
        ),
        migrations.RemoveField(
            model_name="tripartiteinfo",
            name="college_name",
        ),
        migrations.RemoveField(
            model_name="tripartiteinfo",
            name="company_category",
        ),
        migrations.RemoveField(
            model_name="tripartiteinfo",
            name="company_scale",
        ),
        migrations.RemoveField(
            model_name="tripartiteinfo",
            name="job_category",
        ),
        migrations.RemoveField(
            model_name="tripartiteinfo",
            name="major_name",
        ),
        migrations.RemoveField(
            model_name="tripartiteinfo",
            name="upload_time",
        ),
        migrations.AddField(
            model_name="tripartiteinfo",
            name="college",
            field=models.CharField(default="材料学院", max_length=64, verbose_name="学院"),
        ),
        migrations.AddField(
            model_name="tripartiteinfo",
            name="companySize",
            field=models.CharField(default="中", max_length=20, verbose_name="公司规模"),
        ),
        migrations.AddField(
            model_name="tripartiteinfo",
            name="companyType",
            field=models.CharField(default="互联网", max_length=30, verbose_name="公司类别"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="tripartiteinfo",
            name="major",
            field=models.CharField(
                default="计算机科学与技术", max_length=64, verbose_name="专业名称"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="tripartiteinfo",
            name="positionType",
            field=models.CharField(default="研发", max_length=30, verbose_name="岗位类别"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="tripartiteinfo",
            name="status",
            field=models.IntegerField(default=0, verbose_name="审核状态"),
        ),
        migrations.AlterField(
            model_name="tripartiteinfo",
            name="id",
            field=models.AutoField(
                primary_key=True, serialize=False, verbose_name="记录编号"
            ),
        ),
        migrations.AlterField(
            model_name="tripartiteinfo",
            name="salary",
            field=models.CharField(max_length=20, verbose_name="薪资"),
        ),
    ]
