# Generated by Django 5.0.2 on 2025-04-09 19:49

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0004_rename_company_location_tripartiteinfo_companylocation_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="tripartiteinfo",
            options={"verbose_name": "三方信息", "verbose_name_plural": "三方信息"},
        ),
        migrations.RenameField(
            model_name="tripartiteinfo",
            old_name="studentIdCard",
            new_name="student_id_card",
        ),
        migrations.RemoveField(
            model_name="tripartiteinfo",
            name="companyLocation",
        ),
        migrations.RemoveField(
            model_name="tripartiteinfo",
            name="companySize",
        ),
        migrations.RemoveField(
            model_name="tripartiteinfo",
            name="companyType",
        ),
        migrations.RemoveField(
            model_name="tripartiteinfo",
            name="positionName",
        ),
        migrations.RemoveField(
            model_name="tripartiteinfo",
            name="positionType",
        ),
        migrations.RemoveField(
            model_name="tripartiteinfo",
            name="studentName",
        ),
        migrations.AddField(
            model_name="tripartiteinfo",
            name="company_category",
            field=models.CharField(default="互联网", max_length=100, verbose_name="公司类别"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="tripartiteinfo",
            name="company_location",
            field=models.CharField(default="北京", max_length=200, verbose_name="公司所在地"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="tripartiteinfo",
            name="company_scale",
            field=models.CharField(default="中型", max_length=100, verbose_name="公司规模"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="tripartiteinfo",
            name="create_time",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="创建时间",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="tripartiteinfo",
            name="position_category",
            field=models.CharField(default="研发岗", max_length=100, verbose_name="岗位类别"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="tripartiteinfo",
            name="position_name",
            field=models.CharField(default="测试", max_length=100, verbose_name="岗位名称"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="tripartiteinfo",
            name="student_name",
            field=models.CharField(default="null", max_length=100, verbose_name="学生姓名"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="tripartiteinfo",
            name="college",
            field=models.CharField(max_length=200, verbose_name="学院"),
        ),
        migrations.AlterField(
            model_name="tripartiteinfo",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="tripartiteinfo",
            name="major",
            field=models.CharField(max_length=200, verbose_name="专业名称"),
        ),
        migrations.AlterField(
            model_name="tripartiteinfo",
            name="salary",
            field=models.CharField(max_length=50, verbose_name="薪资"),
        ),
        migrations.AlterField(
            model_name="tripartiteinfo",
            name="school",
            field=models.CharField(max_length=200, verbose_name="学生所在学校"),
        ),
        migrations.AlterField(
            model_name="tripartiteinfo",
            name="status",
            field=models.CharField(default="待审核", max_length=20, verbose_name="审核状态"),
        ),
        migrations.AlterField(
            model_name="tripartiteinfo",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="app.students",
                verbose_name="学生",
            ),
        ),
    ]
