# Generated by Django 5.0.2 on 2025-04-27 00:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0005_alter_tripartiteinfo_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="majors",
            name="college",
            field=models.ForeignKey(
                db_column="college_id",
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="app.colleges",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="students",
            name="name",
            field=models.CharField(default="马知遥", max_length=20, verbose_name="姓名"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="students",
            name="phone_number",
            field=models.CharField(
                default=18291786543, max_length=11, verbose_name="联系电话"
            ),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name="Class",
            fields=[
                (
                    "class_id",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="班级编号"
                    ),
                ),
                ("class_name", models.CharField(max_length=32, verbose_name="班级名称")),
                (
                    "major",
                    models.ForeignKey(
                        db_column="major_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app.majors",
                    ),
                ),
            ],
            options={
                "db_table": "class",
            },
        ),
        migrations.AddField(
            model_name="students",
            name="class_id",
            field=models.ForeignKey(
                db_column="class_id",
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="app.class",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="tripartiteinfo",
            name="class_id",
            field=models.ForeignKey(
                db_column="class_id",
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="app.class",
            ),
            preserve_default=False,
        ),
    ]
