# Generated by Django 5.0.2 on 2025-04-27 00:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0006_majors_college_students_name_students_phone_number_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="users",
            name="id",
            field=models.AutoField(
                primary_key=True, serialize=False, verbose_name="用户id"
            ),
        ),
    ]
