# Generated by Django 5.0.2 on 2025-05-02 23:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0007_alter_users_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="students",
            name="gender",
            field=models.CharField(default="女", max_length=4, verbose_name="用户性别"),
        ),
        migrations.AddField(
            model_name="tripartiteinfo",
            name="company_name",
            field=models.CharField(
                default="西安腾讯云计算有限公司", max_length=200, verbose_name="公司名称"
            ),
        ),
    ]
