# Generated by Django 5.0.2 on 2025-05-02 23:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0008_students_gender_tripartiteinfo_company_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="majors",
            name="college",
            field=models.ForeignKey(
                db_column="colleges_id",
                on_delete=django.db.models.deletion.CASCADE,
                to="app.colleges",
            ),
        ),
    ]
