# Generated by Django 5.0.2 on 2025-05-03 00:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0009_alter_majors_college"),
    ]

    operations = [
        migrations.AddField(
            model_name="tripartiteinfo",
            name="gender",
            field=models.CharField(default="女", max_length=20, verbose_name="性别"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="tripartiteinfo",
            name="phone_number",
            field=models.IntegerField(default=12345678, verbose_name="电话"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="majors",
            name="college",
            field=models.ForeignKey(
                db_column="college_id",
                on_delete=django.db.models.deletion.CASCADE,
                to="app.colleges",
            ),
        ),
        migrations.AlterField(
            model_name="tripartiteinfo",
            name="class_id",
            field=models.ForeignKey(
                db_column="class",
                on_delete=django.db.models.deletion.CASCADE,
                to="app.class",
                verbose_name="班级",
            ),
        ),
    ]
