# Generated by Django 5.0.2 on 2025-05-03 01:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0010_tripartiteinfo_gender_tripartiteinfo_phone_number_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="tripartiteinfo",
            name="class_name",
            field=models.CharField(
                db_column="class", default="计算机214", max_length=20, verbose_name="所在班级"
            ),
        ),
        migrations.AlterField(
            model_name="tripartiteinfo",
            name="class_id",
            field=models.ForeignKey(
                db_column="class_id",
                on_delete=django.db.models.deletion.CASCADE,
                to="app.class",
                verbose_name="班级",
            ),
        ),
        migrations.AlterField(
            model_name="tripartiteinfo",
            name="gender",
            field=models.CharField(
                default="西安腾讯云计算有限公司", max_length=20, verbose_name="性别"
            ),
        ),
    ]
