# Generated by Django 5.0.2 on 2025-05-06 20:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0011_tripartiteinfo_class_name_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="tripartiteinfo",
            options={},
        ),
        migrations.AddField(
            model_name="companies",
            name="introduce",
            field=models.CharField(
                default="公司创立于2000年,是行业领先的基础设施和智能终端供应商。",
                max_length=200,
                verbose_name="公司简介",
            ),
        ),
        migrations.AlterField(
            model_name="tripartiteinfo",
            name="class_name",
            field=models.CharField(
                db_column="class_name",
                default="计算机214",
                max_length=20,
                verbose_name="所在班级",
            ),
        ),
    ]
