# Generated by Django 5.0.2 on 2025-05-12 20:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0012_alter_tripartiteinfo_options_companies_introduce_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="students",
            name="graduation_year",
            field=models.IntegerField(
                blank=True, default=2025, null=True, verbose_name="毕业年份"
            ),
        ),
        migrations.AddField(
            model_name="tripartiteinfo",
            name="graduation_year",
            field=models.CharField(default=2025, max_length=4, verbose_name="毕业年份"),
            preserve_default=False,
        ),
    ]
